version: "3.7"

services:
  client_web:
    depends_on:
      - "server"
    build:
      context: ./Frontend
      dockerfile: ./DockerfileDev
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=80
    volumes:
      - ./Frontend/src:/src/
      - ./Frontend/public:/public/
    networks:
      - api
    restart: on-failure

  server:
    depends_on:
      - "mongodb"
    build:
      context: ./Backend/
      dockerfile: ./DockerfileDev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./Backend/index.js:/app/index.js
      - ./Backend/Controllers:/app/Controllers/
      - ./Backend/Models:/app/Models/
      - ./Backend/Routes:/app/Routes/
    networks:
      - api
      - bdd
    env_file:
      - ./Backend/.env
    environment:
      - IS_TEST="TRUE"
    restart: on-failure

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
        - ./.docker/mongodb/data/db/:/data/db/
        - ./.docker/mongodb/data/log/:/var/log/mongodb/
        - ./.docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
        - .env
    networks:
      - bdd
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
        MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    ports:
        - "27017:27017"
    restart: on-failure

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    volumes:
      - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - bdd

networks:
  api:
  bdd:
