version: "3.7"

services:
  client_web:
    depends_on:
      - "server"
    build:
      context: ./Frontend
      dockerfile: ./DockerfileDev
    ports:
      - 80:80
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: "development"
      PORT: 80
    env_file:
      - ./Frontend/.env
    volumes:
      - ./Frontend/src:/src/
      - ./Frontend/public:/public/
    networks:
      - api
    restart: on-failure

  server:
    depends_on:
      - "mongodb"
      - "minio"
    build:
      context: ./Backend/
      dockerfile: ./DockerfileDev
    ports:
      - "8080:8080"
    env_file:
      - .env
      - ./Backend/.env
    volumes:
      - ./Backend/index.js:/app/index.js
      - ./Backend/Controllers:/app/Controllers/
      - ./Backend/Models:/app/Models/
      - ./Backend/Configs:/app/Configs/
      - ./Backend/Routes:/app/Routes/
    networks:
      - api
      - bdd
    environment:
      - IS_TEST="TRUE"
    restart: on-failure

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
        - ./.docker/mongodb/data/db/:/data/db/
        - ./.docker/mongodb/data/log/:/var/log/mongodb/
        - ./.docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
        - .env
    networks:
      - bdd
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
        MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    ports:
        - "27017:27017"
    restart: on-failure

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    volumes:
      - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - bdd

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    network_mode: host
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    command: listen --forward-to localhost:8080/payment/webhook

  minio:
    image: minio/minio
    restart: on-failure
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.docker/storage/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server .docker/storage/minio --console-address ":9001"
    networks:
      - api

  mc:
    container_name: minio-mc
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - "./minio-mc.txt:/tmp/minio-mc.txt"
    networks:
      - api
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 ROOTNAME CHANGEME123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rb --force myminio/bv-finished-products;
      /usr/bin/mc mb myminio/bv-finished-products;
      /usr/bin/mc policy set private myminio/bv-finished-products;
      /usr/bin/mc rb --force myminio/bv-streaming-video-source;
      /usr/bin/mc mb myminio/bv-streaming-video-source;
      /usr/bin/mc policy set private myminio/bv-streaming-video-source;
      /usr/bin/mc rb --force myminio/bv-thumbnail-project;
      /usr/bin/mc mb myminio/bv-thumbnail-project;
      /usr/bin/mc policy set private myminio/bv-thumbnail-project;
      exit 0;
      "
networks:
  api:
  bdd:
