const Errors = {

    //Project : 0
    PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
    PROJECT_NOT_YOURS: "PROJECT_NOT_YOURS",

    //Collaboration : 1
    COLLABORATION_NOT_FOUND: "COLLABORATION_NOT_FOUND",
    COLLABORATION_ALREADY_EXISTS: "COLLABORATION_ALREADY_EXISTS",
    COLLABORATION_NOT_LINKED_TO_PROJECT: "COLLABORATION_NOT_LINKED_TO_PROJECT",
    COLLABORATION_CANT_BE_CHANGED_YOURS: "COLLABORATION_CANT_BE_CHANGED_YOURS",

    //Custom errors : 2
    INTERNAL_ERROR: "INTERNAL_ERROR",
    BAD_REQUEST_MISSING_INFOS: "BAD_REQUEST_MISSING_INFOS",
    BAD_REQUEST_BAD_INFOS: "BAD_REQUEST_BAD_INFOS",
    CANT_GIVE_OWNER_AT_CREATION: "CANT_GIVE_OWNER_AT_CREATION",

    //Rights : 3
    ROLE_UNAUTHORIZED: "ROLE_UNAUTHORIZED",

    //User : 4
    USER_NOT_LOGIN: "USER_NOT_LOGIN",
    USER_NOT_FOUND: "USER_NOT_FOUND",

    LIST_NOT_FOUND: "LIST_NOT_FOUND",
    LIST_NOT_YOURS: "LIST_NOT_YOURS",
    PROJECT_LISTED_NOT_FOUND: "PROJECT_LISTED_NOT_FOUND",
    PROJECT_LISTED_ALREADY_EXISTS: "PROJECT_LISTED_ALREADY_EXISTS",
    LIST_MEMBER_ALREADY_EXISTS: "LIST_MEMBER_ALREADY_EXISTS",
    LIST_MEMBER_NOT_FOUND: "LIST_MEMBER_NOT_FOUND",
    LIST_MEMBER_NOT_LINKED_TO_LIST: "LIST_MEMBER_NOT_LINKED_TO_LIST",
    LIST_MEMBER_CANT_BE_CHANGED_YOURS: "LIST_MEMBER_CANT_BE_CHANGED_YOURS",

    //Image : 6
    IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
    IMAGE_NOT_YOURS: "IMAGE_NOT_YOURS",
};

exports.Errors = Errors;