
name: docker-compose-test-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup de l'environnement de test
        uses: actions/checkout@v2
      - name: Check running containers
        run: docker ps
      - name: Build the stack
        run: docker-compose -f docker-compose-test.yaml up --build -d
